### ISSUE TITLE
下载demo运行后出现NSURLErrorDomain error -999.求解，谢谢

### ISSUE THREAD

**Issue by Mzxer** [GeeTeam/gtapp-ios-oc#4]

**Comment by NikoXu** [comment]
NSURLErrorCancelled, error.code ＝ －999
这个错误请直接忽略.
这个是当异步加载取消时返回。当webview异步加载资源时执行取消操作，Webkit框架的委托将收到此错误。
在我们sdk里, 过早的关闭验证会导致这个错误。
@SYZeng
